version: '3.7'
services:

  portainer:
    image: portainer/portainer-ce:latest
    volumes:
      - $DSOCK:/var/run/docker.sock
      - $DAPPS/portainer/data:/data
    container_name: portainer
    networks:
       proxy:
    ports:
      - '9000:9000'
      - '9443:9443'
    restart: always
    security_opt:
      - no-new-privileges:true

  whoami:
    image: "traefik/whoami"
    command:
      - --port=8086
    container_name: whoami
    networks:
       proxy:
    ports:
      - '8086:8086'
    restart: always

  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: monitor.home.lab
    ports:
      - 19999:19999
    expose:
      - 19999
    restart: unless-stopped
    networks:
      - proxy
      - internal
#    pid: host
    environment:
      PGID: 998
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - $DAPPS/netdata/netdataconfig:/etc/netdata
      - $DAPPS/netdata/netdatalib:/var/lib/netdata
      - $DAPPS/netdata/netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - $DSOCK:/var/run/docker.sock:ro

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
