---
version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=$PGUID
      - PGID=$PGUID
      - TZ=$TZ
    volumes:
      - $DAPPS/nextcloud/config:/config
      - $DAPPS/nextcloud/data:/data
    ports:
      - 8443:443
    restart: unless-stopped
